[package]
name = "golutra-llm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
eventsource-stream.workspace = true
futures-util.workspace = true
genai.workspace = true
golutra-auth = { path = "../golutra-auth" }
golutra-core.workspace = true
reqwest.workspace = true
reqwest13.workspace = true
rustls.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
