[package]
name = "golutra-vis"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
golutra-client = { path = "../golutra-client", version = "0.1.0" }
golutra-core.workspace = true
golutra-protocol.workspace = true
golutra-tools = { path = "../golutra-tools", version = "0.1.0" }
miette.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
